### PR TITLE
Fixes poms configurations

### PR DESCRIPTION
**Pull request by otaviojava**
Fixes poms configurations

### CODE REVIEW

**Comment by keilw** [comment]
Sorry but a "java EE 7 compliant" Midas will not use Moneta, as it won't run under SE 7.

**Comment by otaviojava** [comment]
As I told you, this depeency is as provided, so you can use the bk implementation.

**Comment by otaviojava** [comment]
@keilw nothing on this implementation need the Java 8 to run out.

**Comment by keilw** [comment]
Anyway, moneta.jar won't run in Java 7 because it was built against Java 8.

**Comment by otaviojava** [comment]
Yes, you are right :)

**Pull request merged**
